# Generated by Django 5.2.6 on 2025-09-15 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(choices=[('nikey', 'Nikey'), ('adidas', 'Adidas'), ('puma', 'Puma'), ('reebok', 'Reebok')], default='No Brand', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('topwear', 'Topwear'), ('bottomwear', 'Bottomwear'), ('shoes', 'Shoes'), ('accessories', 'Accessories')], default='Uncategorized', max_length=100),
        ),
    ]
