# Generated by Django 5.2.6 on 2025-09-09 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_product_category'),
        ('main', '0005_initial_product_data'),
    ]

    operations = [
    ]
